import Link from 'next/link';
import { getAuditLogs, getLedgerEntries, getNotifications, getSellerApplications, getTrades, getUsers, getWithdrawals, getWorkerRuns, formatMoney, formatSats, getRiskFlags, getLedgerTotals } from '@/lib/data';
import { ledgerAudit } from '@/lib/ledger';
import { getCsrfToken } from '@/lib/api/csrf';
export async function AdminStats(){ const trades:any[]=await getTrades(); const risks:any[]=await getRiskFlags(); const disputes=trades.filter(t=>t.status==='DISPUTED'||t.status==='ADMIN_REVIEW').length; const locked=trades.reduce((s,t)=>['RELEASED','CANCELLED','EXPIRED','REFUNDED','RESOLVED_SELLER','RESOLVED_BUYER'].includes(t.status)?s:s+t.btcAmountSats,0); return <div className="stats"><div><b>{trades.length}</b><span>DB trades</span></div><div><b>{disputes}</b><span>disputes/reviews</span></div><div><b>{formatSats(locked)}</b><span>fake locked BTC</span></div><div><b>{risks.length}</b><span>risk flags</span></div></div> }
export async function AdminTrades(){ const trades:any[]=await getTrades(); return <table className="data-table"><thead><tr><th>Trade</th><th>Status</th><th>Buyer</th><th>Seller</th><th>Amount</th><th>Risk</th><th>Actions</th></tr></thead><tbody>{trades.map(t=><tr key={t.id}><td>{t.id}</td><td>{t.status}</td><td>{t.buyer}</td><td>{t.seller}</td><td>{formatMoney(t.fiatAmount,t.currency)}</td><td>{t.risk}</td><td><Link href={`/trades/${t.id}`}>Open</Link></td></tr>)}</tbody></table> }
export async function AdminUsers(){ const users:any[]=await getUsers(); return <table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Seller</th><th>Trades</th><th>Risk</th><th>Profile</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.role}</td><td>{u.status}</td><td>{u.sellerStatus}</td><td>{u.trades}</td><td>{u.riskLevel}</td><td><Link href={`/traders/${u.username}`}>View</Link></td></tr>)}</tbody></table> }
export async function LedgerTable(){ const entries:any[]=await getLedgerEntries(); return <table className="data-table"><thead><tr><th>Group</th><th>Account</th><th>Direction</th><th>Sats</th><th>Reason</th><th>Trade</th></tr></thead><tbody>{entries.map((e)=><tr key={e.id}><td>{e.groupId}</td><td>{e.account}</td><td>{e.direction}</td><td>{e.sats}</td><td>{e.reason}</td><td>{e.tradeId||''}</td></tr>)}</tbody></table> }
export async function LedgerAuditTable(){ const groups=await ledgerAudit(); const totals=await getLedgerTotals(); return <><table className="data-table"><thead><tr><th>Group</th><th>Balance</th><th>Status</th></tr></thead><tbody>{groups.map(g=><tr key={g.group}><td>{g.group}</td><td>{g.balance}</td><td>{g.balance===0?'balanced':'broken'}</td></tr>)}</tbody></table><h3>Account totals</h3><table className="data-table"><tbody>{Object.entries(totals).map(([k,v])=><tr key={k}><td>{k}</td><td>{String(v)}</td></tr>)}</tbody></table></> }
export async function SellerApplicationsTable(){ const apps:any[]=await getSellerApplications(); const csrf=await getCsrfToken(); return <table className="data-table"><thead><tr><th>Application</th><th>User</th><th>Status</th><th>Markets</th><th>Methods</th><th>Expected volume</th><th>Actions</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td>{a.id}</td><td>{a.username}</td><td>{a.status}</td><td>{a.markets}</td><td>{a.paymentMethods}</td><td>{a.expectedVolume}</td><td><form method="post" action={`/api/admin/seller-applications/${a.id}/approve`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={a.status!=='pending'}>Approve</button></form><form method="post" action={`/api/admin/seller-applications/${a.id}/reject`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={a.status!=='pending'}>Reject</button></form></td></tr>)}</tbody></table> }
export async function AuditLogTable(){ const logs:any[]=await getAuditLogs(); return <table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody>{logs.slice(0,50).map(l=><tr key={l.id}><td>{l.createdAt}</td><td>{l.actor}</td><td>{l.action}</td><td>{l.target}</td><td>{l.details}</td></tr>)}</tbody></table> }
export async function NotificationsTable(){ const notes:any[]=await getNotifications(); return <table className="data-table"><thead><tr><th>Time</th><th>Channel</th><th>Event</th><th>Recipient</th><th>Status</th><th>Payload</th></tr></thead><tbody>{notes.slice(0,30).map(n=><tr key={n.id}><td>{n.createdAt}</td><td>{n.channel}</td><td>{n.event}</td><td>{n.recipient}</td><td>{n.status}</td><td>{n.payload}</td></tr>)}</tbody></table> }
export async function WithdrawalsTable(){ const withdrawals:any[]=await getWithdrawals(); const csrf=await getCsrfToken(); return <table className="data-table"><thead><tr><th>ID</th><th>User</th><th>Address</th><th>Amount</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody>{withdrawals.map(w=><tr key={w.id}><td>{w.id}</td><td>{w.userId}</td><td><code>{w.address}</code></td><td>{formatSats(w.amountSats)}</td><td>{formatSats(w.feeSats)}</td><td>{w.status}</td><td><form method="post" action={`/api/admin/withdrawals/${w.id}/approve`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={w.status!=='pending_admin_review'}>Approve mock</button></form><form method="post" action={`/api/admin/withdrawals/${w.id}/reject`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={w.status!=='pending_admin_review'}>Reject</button></form></td></tr>)}</tbody></table> }
export async function WorkerRunsTable(){ const runs:any[]=await getWorkerRuns(); return <table className="data-table"><thead><tr><th>Time</th><th>Worker</th><th>Status</th><th>Details</th></tr></thead><tbody>{runs.slice(0,30).map(r=><tr key={r.id}><td>{r.createdAt}</td><td>{r.worker}</td><td>{r.status}</td><td>{r.details}</td></tr>)}</tbody></table> }
