import { findTrade, formatMoney, formatSats, getEvidence, getTradeMessages } from '@/lib/data';
import { riskForTrade, riskScore, riskLabel } from '@/lib/risk';
import { getCsrfToken } from '@/lib/api/csrf';
export async function TradeRoom({id}:{id:string}){
 const trade:any = await findTrade(id); if(!trade) return <div className="box">Trade not found.</div>;
 const flags:any[] = await riskForTrade(trade.id); const score = await riskScore(trade.id);
 const messages:any[] = await getTradeMessages(trade.id);
 const evidence:any[] = await getEvidence(trade.id);
 const csrf = await getCsrfToken();
 const terminal = ['RELEASED','CANCELLED','EXPIRED','REFUNDED','RESOLVED_BUYER','RESOLVED_SELLER'].includes(trade.status);
 return <div className="trade-grid"><section className="box"><h2>Trade {trade.id}</h2><dl><dt>Status</dt><dd><b>{trade.status}</b></dd><dt>Buyer pays</dt><dd>{formatMoney(trade.fiatAmount,trade.currency)}</dd><dt>Escrow locked</dt><dd>{formatSats(trade.btcAmountSats)}</dd><dt>Buyer receives</dt><dd>{formatSats(trade.buyerReceivesSats)}</dd><dt>Platform fee</dt><dd>{formatSats(trade.feeSats)}</dd><dt>Payment method</dt><dd>{trade.paymentMethod}</dd><dt>Timer</dt><dd>{trade.deadline}</dd><dt>Risk</dt><dd>{riskLabel(score)} ({score})</dd></dl><div className="button-row"><form method="post" action={`/api/trades/${trade.id}/mark-paid`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={terminal}>Mark paid</button></form><form method="post" action={`/api/trades/${trade.id}/release`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={terminal}>Release BTC</button></form><form method="post" action={`/api/trades/${trade.id}/dispute`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={terminal}>Open dispute</button></form><form method="post" action={`/api/trades/${trade.id}/cancel`}><input type="hidden" name="_csrf" value={csrf}/><button disabled={terminal}>Cancel</button></form></div><h3>Feedback</h3><form className="stack" method="post" action={`/api/trades/${trade.id}/feedback`}><input type="hidden" name="_csrf" value={csrf}/><select name="rating" defaultValue="1"><option value="1">positive</option><option value="0">neutral</option><option value="-1">negative</option></select><input name="comment" defaultValue="Local test feedback"/><button>Save feedback</button></form></section><section className="box"><h2>Trade chat</h2><div className="chat">{messages.map(m=><p key={m.id}><b>{m.sender}:</b> {m.body}<br/><small>{m.createdAt}</small></p>)}</div><form className="stack" method="post" action={`/api/trades/${trade.id}/messages`}><input type="hidden" name="_csrf" value={csrf}/><textarea name="body" placeholder="Message stays inside the trade room" /><button>Send local message</button></form></section><aside className="box"><h2>Evidence and risk</h2>{flags.length ? <ul>{flags.map(f=><li key={f.id}><b>{f.severity}</b>: {f.details}</li>)}</ul> : <p>No active flags.</p>}<h3>Evidence</h3>{evidence.length ? <ul>{evidence.map(e=><li key={e.id}><b>{e.kind}</b>: {e.description}<br/><small>{e.uploader} · {e.createdAt}</small></li>)}</ul> : <p>No evidence uploaded.</p>}<form className="stack" method="post" action={`/api/trades/${trade.id}/evidence`} encType="multipart/form-data"><input type="hidden" name="_csrf" value={csrf}/><select name="kind"><option>receipt</option><option>bank statement</option><option>chat note</option><option>admin note</option></select><input type="file" name="file"/><textarea name="description" placeholder="Describe local evidence."/><button>Attach evidence</button></form><h3>Timeline</h3><ol><li>Trade created</li><li>Escrow locked</li><li>Current state: {trade.status}</li></ol></aside></div>
}
