export const TRADE_STATES = [
  'OFFER_OPEN','TRADE_CREATED','WAITING_SELLER_ESCROW','ESCROW_PENDING_CONFIRMATION','ESCROW_FUNDED','WAITING_BUYER_PAYMENT','BUYER_MARKED_PAID','WAITING_SELLER_RELEASE','RELEASE_PENDING','RELEASED','CANCELLED','EXPIRED','DISPUTED','ADMIN_REVIEW','RESOLVED_BUYER','RESOLVED_SELLER','REFUNDED'
] as const;
export type TradeState = typeof TRADE_STATES[number];

export const TRANSITIONS: Record<TradeState, TradeState[]> = {
  OFFER_OPEN: ['TRADE_CREATED'],
  TRADE_CREATED: ['WAITING_SELLER_ESCROW','CANCELLED','EXPIRED'],
  WAITING_SELLER_ESCROW: ['ESCROW_PENDING_CONFIRMATION','CANCELLED','EXPIRED','DISPUTED'],
  ESCROW_PENDING_CONFIRMATION: ['ESCROW_FUNDED','DISPUTED'],
  ESCROW_FUNDED: ['WAITING_BUYER_PAYMENT','DISPUTED'],
  WAITING_BUYER_PAYMENT: ['BUYER_MARKED_PAID','CANCELLED','EXPIRED','DISPUTED'],
  BUYER_MARKED_PAID: ['WAITING_SELLER_RELEASE','DISPUTED'],
  WAITING_SELLER_RELEASE: ['RELEASE_PENDING','DISPUTED'],
  RELEASE_PENDING: ['RELEASED','DISPUTED'],
  RELEASED: [],
  CANCELLED: [],
  EXPIRED: [],
  DISPUTED: ['ADMIN_REVIEW'],
  ADMIN_REVIEW: ['RESOLVED_BUYER','RESOLVED_SELLER','REFUNDED'],
  RESOLVED_BUYER: [],
  RESOLVED_SELLER: [],
  REFUNDED: []
};

export function canTransition(from: TradeState, to: TradeState){
  return TRANSITIONS[from].includes(to);
}

export function assertTransition(from: TradeState, to: TradeState){
  if(!canTransition(from, to)) throw new Error(`Illegal trade transition: ${from} -> ${to}`);
}
